version: "2"
services:
  nodecv:
    build: .
    #image: "siomiz/node-opencv:2.4.x"
    container_name: "nodecv"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: bash -c "cd /app;npm install;node server/server.js"
    restart: always